---
name: 📖 Code
on:
  push:
    paths: '.github/workflows/code.yml'
  workflow_dispatch: {}
  schedule:
    - cron: "30 4 * * 4"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deps:
    timeout-minutes: 30
    environment: code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: ⚡ Dependencies
        run: |
          apt update -yq; sudo apt-get install -yq zsh tree
          curl -sL https://trunk.io/releases/trunk -o ~/trunk
          chmod a+x ~/trunk; sudo make -C lib/zsdoc install
      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@3068fa83f9cbd7ae106cac45483635a2f3a195c9
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: 📝 Install asciidoctor-pdf and rouge
        run: gem install asciidoctor-pdf rouge
      - name: ♻️ Generate Code
        run: |
          make -C code
          make -C code clean
          ~/trunk upgrade; ~/trunk check --all --fix --ci
      - name: ✨ Trunk Check
        uses: trunk-io/trunk-action@22e948f7bb9f870bc6c42625585f1ef27e9c5afc
      - name: 🏗 Compress code documentation
        run: tar cvzf code.tar.gz code
      - name: 📤 Upload code.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: code documentation
          path: code.tar.gz
      - name: "🆗 Commit"
        uses: z-shell/.github/actions/commit@v1.0.0
        with:
          commitMessage: Code ${{ github.sha }}
          workDir: code
          commitUserName: ${{ secrets.ACTIONS_USER }}
          commitUserEmail: ${{ secrets.ACTIONS_MAIL }}
