---
name: 🚀 Deploy Code to GH Pages

on:
  workflow_run:
    workflows:
      - "📖 Code"
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: ♻️ Prepare
        run: |
          command mkdir -p gh-pages/code gh-pages/zsh
          command cp -vrf code/zsdoc/html gh-pages/code/
      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./gh-pages
          allow_empty_commit: true
          keep_files: true
          user_name: ${{ secrets.ACTIONS_USER }}
          user_email: ${{ secrets.ACTIONS_MAIL }}
