---
name: "⭕ Trunk Check"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 05 * * 5"
  workflow_dispatch:

jobs:
  check:
    name: "⚡"
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    secrets:
      if: github.event.schedule == '0 05 * * 5'
      trunk-token: ${{ secrets.TRUNK_TOKEN }}
