---
name: "⭕ Trunk Check"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  trunk-check:
    name: "⚡Check"
    uses: z-shell/.github/.github/workflows/trunk.yml@main
  trunk-upload:
    name: "⚡Upload"
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    if: ${{ github.repository == 'z-shell/docs' }}
    secrets:
      trunk-token: ${{ secrets.TRUNK_TOKEN }}
