---
name: "⭕ Trunk Check"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  trunk:
    name: "⚡"
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    if: ${{ github.actions.repository == z-shell/docs }}
    secrets:
      trunk-token: ${{ secrets.TRUNK_TOKEN }}
